### ISSUE TITLE
Subscriber form is not registering subscribers [For non-migrated users]

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/wp-maintenance-mode#334]
### Description

Subscribe form is not registering subscribers on the instances which are not migrated to the Gutenberg changes made in the latest update.

The issue was initially reported on the wp.org forum but I was unable to replicate it before; as soon as I was able to I came here to report the issue.

### How to replicate

1. Install a Previous version of the plugin (I tested with v2.4.7).
2. Activate the maintenance mode and enable the subscribe option from Settings > Modules.
3. Open the site in incognito and do some dummy entries and then check the subscriber count, you will observe it is increasing with each entry.
4. Now update the plugin to the latest version(v2.5.3) and don't migrate to the new Gutenberg changes.
5. Go to Modules and empty the subscriber list so the counter is back at 0.
6. Repeat step 3 with this version.
7. You will observe the counter is stuck at 0 and the subscribe form is not registering new subscribers.

### References
[wp-maintenance-mode.2.4.7.zip](https://github.com/Codeinwp/wp-maintenance-mode/files/9717449/wp-maintenance-mode.2.4.7.zip)

The page in version 2.4.7:
![image](https://user-images.githubusercontent.com/110405452/194113396-780b0eee-421e-4fe5-a71c-ca23c0cbf6aa.png)

This notice appears after the email entry[in version 2.4.7]:
![image](https://user-images.githubusercontent.com/110405452/194112854-b9d991e0-e718-442d-b929-59bb241fe025.png)

Subscriber count in v2.4.7:
![image](https://user-images.githubusercontent.com/110405452/194114321-a2584bda-7c27-40f7-922c-7639c23c9ed4.png)

The page in version 2.5.3 (exactly the same ):
![image](https://user-images.githubusercontent.com/110405452/194113689-5d0b17fe-8dd5-403f-9d12-9fd49f544a25.png)

and if you will enter the email in the input field in this version then you will also notice that the notice which says -

> You are successfully subscribed, thanks

doesn't appear as well.

Subscriber count in v2.5.3:
![image](https://user-images.githubusercontent.com/110405452/194114532-071022e7-bc1d-4664-a887-9f137af7d5ae.png)

[Wp.org ticket ](https://wordpress.org/support/topic/wp-maintenance-export-subscribers/)related to the issue.
### Technical info

- WordPress version : 6.0.2
- Plugin: v2.5.3

**Comment by girishpanchal30** [comment]
Hey @kushh23,
I have fixed the subscriber entry issue. Please check with this PR - Codeinwp/wp-maintenance-mode/pull/335 

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested the fix and the subscribe works fine now for non migrated users 🚀

**Comment by kushh23** [comment]
Hey @girishpanchal30 @irinelenache,

I have tried the plugin build and the issue still exists for me .

**Comment by girishpanchal30** [comment]
@kushh23 Can you please share your test instance details here?

**Comment by kushh23** [comment]
Hey @girishpanchal30,

I decided to do some more testing, so I deactivated it, and then after reactivating the plugin it worked for me! So the issue is fixed with the plugin build 🤟🙌

Thanks

**Comment by kushh23** [comment]
Closing this as the bug is fixed and the new version is also released 10 days ago
