### ISSUE TITLE
Revise plugin Installation step in Onboarding for compliance

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/wp-maintenance-mode#490]
@girishpanchal30  we need to make changes for the onboarding of this plugin. The current implementation installs and activates the Otter Blocks and Optimole plugins without explicitly informing the user or providing a clear option to opt-out.

The goal is to make the installation of these plugins transparent and optional.

The following changes must be implemented in the "Select the type of page you want" step of the setup wizard which currently looks like this:

<img width="1201" height="777" alt="Image" src="https://github.com/user-attachments/assets/fe65518e-2966-4820-9f15-04fdc9e6cc84" />

### 1. Introduce Explicit Consent Checkboxes:
A new checkbox must be added to the screen. Both the new and existing checkboxes should be checked by default.

Checkbox 1: Essential Page Templates (Otter Blocks)

**Label/Text:**  Pick a template to get started. <a href=“#”> Otter Blocks</a> plugin will be installed and activated to support and customize your layout.
It also unlocks tools like forms and popups - if you need them later.		

### Checkbox 2: Image and speed optimisation (Optimole)

**Label/Text:** Templates would have pre-optimized images and all of your website’s images would be delivered via Amazon Cloudfront CDN, resulting in an ≈ 80% increase in speed. <a href=“#”> Optimole</a> plugin will be installed and activated.

### 2. Implement Conditional UI for Template Selection:
The visibility of the template picker section will be dependent on the "Essential Page Templates" checkbox.

If the Otter Blocks checkbox is checked, the template selection area remains visible and functional.

<img width="1020" height="674" alt="Image" src="https://github.com/user-attachments/assets/5c87139c-0071-4b57-b71a-059b2ee4901b" />

If the Otter Blocks checkbox is unchecked, the entire template selection area below it should be faded:

<img width="1071" height="691" alt="Image" src="https://github.com/user-attachments/assets/44086a1d-319c-42b0-a285-f6970f7cc3f6" />

### 3. Conditional Plugin Installation Logic:
The installation logic must be tied to the final state of these checkboxes when the user proceeds.

Otter Blocks should only be installed and activated if its corresponding checkbox is checked.
Optimole should only be installed and activated if its corresponding checkbox is checked.

HTML code for Reference: [Pastebin](https://pastebin.com/k2FYrSnS).

**Comment by vytisbulkevicius** [comment]
@girishpanchal30 please prioritize this

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I have revised onboarding steps with this PR https://github.com/Codeinwp/wp-maintenance-mode/pull/491

**Comment by vytisbulkevicius** [comment]
Thanks @girishpanchal30 , looks good, I haven't emphasized about the change of the 2nd button.

The "I don't want to use a template" button should be "Skip this step" like in the provided screenshot:

<img width="450" height="65" alt="Image" src="https://github.com/user-attachments/assets/a01250d1-0fed-41c4-8853-9779a83088d6" />

Also, I found this issue, so when I click "Continue" with this configuration:

<img width="1228" height="877" alt="Image" src="https://github.com/user-attachments/assets/67775e86-f09c-4c4e-a466-414bc1d510d3" />


I get a blank page when visiting my website:

<img width="1631" height="818" alt="Image" src="https://github.com/user-attachments/assets/df3f6c84-193d-4f2b-8e1a-e40b4e352780" />

It should behave the same as you would click the "I don't want to use a template" (which should become "Skip this step") leading to the Maintenance notification showing up on the front-end (for non-logged in users, of course):

<img width="1153" height="549" alt="Image" src="https://github.com/user-attachments/assets/cb1c92e6-e7c2-4598-97ac-f13a79aba109" />

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I have fixed the mentioned issues with the latest commit. Please check and let me know if any issues occurred.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I have fixed it with the latest commit.

**Comment by vytisbulkevicius** [comment]
@girishpanchal30 evverything looks good now but I still see this error when clicking "Continue" if I leave the checkbox to install Otter:

<img width="504" height="146" alt="Image" src="https://github.com/user-attachments/assets/7c8760fd-b6ef-4541-b4f1-f039592a1662" />

It proceeds to the next steps and Otter is installed succesfully, everything seems to be fine but this error appears for some reason, I checked that it doesn't happen with the current production version of the plugin.

It doesn't show up if I keep only Optimole to be installed so should be related to Otter installation.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I have tested it with both local and tasteWP instances, but I can't reproduce it. Can you please provide your instance details?

Thank you!
